#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
